### ISSUE TITLE
使用后编译安装时，npm run dev报错

### ISSUE THREAD

**Issue by py419569317** [didi/cube-ui#46]
场景：
1、按照cube-ui文档的后编译四个步骤安装
2、不同之处在于.babelrc文件的plugin是这么配置的，保留了默认的transform-runtime(不知道使用了babel-polyfill之后这么配置是否多此一举)
```
"plugins": ["transform-runtime", ["transform-modules", {
    "cube-ui": {
      // 注意: 这里的路径需要修改到 src/modules 下
      "transform": "cube-ui/src/modules/${member}",
      "kebabCase": true
    }
  }]]
```
3、执行npm run dev
现状：
项目可以正常启动，但是编译的过程中会报错，找了很久没有找到解决方法，请指教
```
{ Error: Cannot find module '/Users/pengyong/Des/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadPkg (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack-post-compile-plugin@0.1.2@webpack-post-compile-plugin/lib/util.js:68:11)
    at /Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack-post-compile-plugin@0.1.2@webpack-post-compile-plugin/lib/util.js:16:17
    at Array.forEach (native)
    at Object.collectDependencies (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack-post-compile-plugin@0.1.2@webpack-post-compile-plugin/lib/util.js:13:9)
    at PostCompilePlugin._collectCompileDependencies (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack-post-compile-plugin@0.1.2@webpack-post-compile-plugin/lib/index.js:47:8)
    at Compiler.<anonymous> (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack-post-compile-plugin@0.1.2@webpack-post-compile-plugin/lib/index.js:20:29)
    at Compiler.applyPluginsAsyncSeries (/Users/pengyong/Desktop/svn/projectPath/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:206:13)
    at Watching._go (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack@3.8.1@webpack/lib/Compiler.js:47:17)
    at Watching.invalidate (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack@3.8.1@webpack/lib/Compiler.js:141:9)
    at watcher.compiler.watchFileSystem.watch (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack@3.8.1@webpack/lib/Compiler.js:122:9)
    at EventEmitter.watcher.once (/Users/pengyong/Desktop/svn/projectPath/node_modules/_webpack@3.8.1@webpack/lib/node/NodeWatchFileSystem.js:45:4)
    at EventEmitter.g (events.js:292:16) code: 'MODULE_NOT_FOUND' }
```
### Specify your

* vue version: 2.4.4
* cube-ui version: 1.0.2

**Comment by dolymood** [comment]
用了 cnpm？

关于第2点，如果加了 polyfill 的话，可以不加 transform-runtime。

**Comment by py419569317** [comment]
谢谢，是cnpm安装的问题
