### ISSUE TITLE
[New Feature] nuxt如何配置后编译

### ISSUE THREAD

**Issue by dagaozi** [didi/cube-ui#520]
### What problem does this feature solve?
nuxt中修改主题色，后编译那部分咋搞，求帮助

### What does the proposed API look like?
nuxt better support

**Comment by dolymood** [comment]
nuxt不能后编译的，可以这样做：
后端的时候不做修改，只有前端运行的代码中是修改主题色的。

**Comment by lxc455735702** [comment]
@dolymood  前端运行的代码修改主题色，是指直接将src下面的theme.styl内的颜色直接替换调吗？
还是如何做？我将前端theme.styl 的颜色替换了 预览也没起到效果。还是需要在webpack 配置些东西？

**Comment by dagaozi** [comment]
> nuxt不能后编译的，可以这样做：
> 后端的时候不做修改，只有前端运行的代码中是修改主题色的。

@dolymood  vue-cli-plugin-cube-ui插件生成的下面这部分的代码，怎么放在nuxt.config.js中，才能让我的自定义样式生效。nuxt.config好像只提供了webpack的扩展配置
module.exports = {
  css: {
    loaderOptions: {
      stylus: {
        'resolve url': true,
        'import': [
          './src/theme'
        ]
      }
    }
  },
  pluginOptions: {
    'cube-ui': {
      postCompile: true,
      theme: true
    }
  }
}

**Comment by dolymood** [comment]
我们弄一个nuxt的示例仓库参考

**Comment by lxc455735702** [comment]
@dolymood 好的，谢谢

**Comment by dagaozi** [comment]
@dolymood  你好，nuxt的示例仓库参考有了吗

**Comment by dolymood** [comment]
我们正在弄，预计明天下班前给到

**Comment by maoamao** [comment]
hello，[nuxt的示例仓库](https://github.com/cube-ui/cube-nuxt-demo)
有问题欢迎继续交流~

**Comment by lxc455735702** [comment]
@maoamao 你好，我克隆了项目之后 本地运行报错
```
 ERROR  Cannot read property 'modulePath' of null                     09:34:57

  at Object.collectTransformModules (node_modules\webpack-transform-modules-plug
in\lib\util.js:25:20)
  at TransformModulesPlugin._collectTransformModules (node_modules\webpack-trans
form-modules-plugin\lib\index.js:151:8)
  at runGetter (node_modules\webpack-transform-modules-plugin\lib\index.js:22:33
)
  at _next1 (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10),
 <anonymous>:21:1)
  at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <
anonymous>:43:1)
  at run (node_modules\webpack-post-compile-plugin\lib\index.js:98:5)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\l
ib\HookCodeFactory.js:33:10), <anonymous>:39:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules\tapable\lib\Hook.js:154:20)
  at Watching._go (node_modules\webpack\lib\Watching.js:41:32)
  at node_modules\webpack\lib\Watching.js:33:9
  at Compiler.readRecords (node_modules\webpack\lib\Compiler.js:479:11)
  at new Watching (node_modules\webpack\lib\Watching.js:30:17)
  at Compiler.watch (node_modules\webpack\lib\Compiler.js:207:10)
  at Compiler.compiler.watch (node_modules\time-fix-plugin\index.js:14:24)
  at node_modules\@nuxt\webpack\dist\webpack.js:5346:35
  at new Promise (<anonymous>)


 ERROR  Cannot read property 'modulePath' of null                     09:34:57

  at Object.collectTransformModules (node_modules\webpack-transform-modules-plug
in\lib\util.js:25:20)
  at TransformModulesPlugin._collectTransformModules (node_modules\webpack-trans
form-modules-plugin\lib\index.js:151:8)
  at runGetter (node_modules\webpack-transform-modules-plugin\lib\index.js:22:33
)
  at _next1 (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10),
 <anonymous>:31:1)
  at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), <
anonymous>:53:1)
  at run (node_modules\webpack-post-compile-plugin\lib\index.js:98:5)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\tapable\l
ib\HookCodeFactory.js:33:10), <anonymous>:49:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules\tapable\lib\Hook.js:154:20)
  at Watching._go (node_modules\webpack\lib\Watching.js:41:32)
  at node_modules\webpack\lib\Watching.js:33:9
  at Compiler.readRecords (node_modules\webpack\lib\Compiler.js:479:11)
  at new Watching (node_modules\webpack\lib\Watching.js:30:17)
  at Compiler.watch (node_modules\webpack\lib\Compiler.js:207:10)
  at Compiler.compiler.watch (node_modules\time-fix-plugin\index.js:14:24)
  at wdm (node_modules\webpack-dev-middleware\index.js:51:33)
  at WebpackBundler.webpackDev (node_modules\@nuxt\webpack\dist\webpack.js:5383:
7)
```

**Comment by maoamao** [comment]
试试把 package.json 中的 nuxt 从 dependencies 下 移到 devDependencies 下

**Comment by lxc455735702** [comment]
@maoamao 可以了。谢谢。
